// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTwit struct {
	ContextText string `json:"contextText"`
	UserID      string `json:"userId"`
}

type NewUser struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

type Twit struct {
	ID              string    `json:"id"`
	ContentText     string    `json:"contentText"`
	PublicationDate time.Time `json:"publicationDate"`
	Author          *User     `json:"author"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Twits []*Twit `json:"twits"`
}
